config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Routes syntax
   # verb 'path', to: 'controller#action'

  # See all task
  get '/tasks', to: 'tasks#index'
  post '/tasks', to: 'tasks#create'
  # See details about one task
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  # Create a task
  post '/tasks', to: 'tasks#create'
  # Update a task
  get '/tasks/:id/edit', to: 'tasks#edit'
  patch '/tasks/:id', to: 'tasks#update'
  # Destroy a task
  delete '/tasks/:id', to: 'tasks#destroy'


   # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
  validates :completed, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for task do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <%= render 'form', task: @task %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="my-5">Task 📝</h1>
  <div class="row">
    <% @tasks.each do |task| %>
      <div class="col-6 col-lg-4">
        <%= link_to task_path(task) do %>
          <div class="shadow rounded p-3 mb-3">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">
              <p><%= task.completed %></p>
              <p><%= task.title %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>My Task</h1>
  <div class="row">
    <div class="col-8">
        <%= render 'form', task: @task %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">

    <h1 class="my-5"><%= @task.title %></h1>
     <hr>

    <p><%= @task.details %> </p>

    <div class="shadow rounded p-3 mb-3">
    <p class="task-task-text display-inline">
      <%= check_box_tag 'completed?', 1, @task.completed, disabled: true, id: "task_complete" %></p>

    </div>


        <%= link_to "➕Add New Task", tasks_new_path(@task), method: 'get', class: "text-center form-control btn-main margin-top-25"%>

</div>